### ISSUE TITLE
Automate Licensing

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/.github#21]
All code in the various NWX repos, that we write, should be licensed under the Apache 2.0 license. AFAIK, the license header needs to be on every source file and a copy of the actual Apache 2.0 license needs to be in a file `LICENSE` located in the top-level repo. Adding the `LICENSE` file can be done manually (it should already exist in all of the repos) since it won't ever need to change, but applying the header should be automate. 

Edit: see https://github.com/CMakePP/CMinx (and https://github.com/CMakePP/.github) for how I did it there.

**Comment by quazirafi** [comment]
Done! May be we can close this!
