### ISSUE TITLE
Clean-up auto-generated __init__.py

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/.github#38]
The auto-generated `__init__.py` file injects some pieces the C++ standard library (`std::array`, `std::vector`, `std::shared_ptr`) into the user's Python module. These elements are injected with no scope protection (e.g., `std.vector`) and may cause problems if user's expose similarly named functions. 

While we're at it, the generated `__init__.py` file does not adhere to PEP8 which makes my IDE flip out.

**Comment by wadejong** [comment]
Will look into dealing with the long lists.

**Comment by keceli** [comment]
Similar to #33, I'll close this since there is no auto-generated python files for PyBind11 bindings.
