### ISSUE TITLE
Update FindCppyy.cmake

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/.github#59]
I suspect this issue affects several repositories so I've opened this issue here. That said, I'm specifically looking at the `FindCppyy.cmake` file in ParallelZone (so if this issue is PZ unique we should move this issue there).

The current `FindCppyy.cmake` is non-standard in at least two regards:

1. The version to find is hard-coded. In typical CMake usage users pass the version to find to `find_package`.
2. It attempts to install Cppyy if it's not found. `FindXXX.cmake` should simply determine if the package can be found or not. Installing should happen in a different module.

**Comment by wavefunction91** [comment]
Query Wim viz exporting `CppyyConfig.cmake`

**Comment by keceli** [comment]
Closing as not planned due to shift to PyBind11.
